#!/usr/bin/env node

/**
 * Dependencies
 */
var exec = require('child_process').exec;


/**
 * Locals
 */
var outputDir = '~/Sites/square2';

// Compile the js.
exec('browserify main.js -o square.js', function cb(error, stdout, stderr) {
	console.log('stdout: ' + stdout);
	console.log('stderr: ' + stderr);
	if (error !== null) {
		console.log('exec error: ' + error);
	}
});

// Copy the entire contents of the dev directory to the output directory.
exec('cp -R ./ ' + outputDir, function cb(error, stdout, stderr) {
	console.log('stdout: ' + stdout);
	console.log('stderr: ' + stderr);
	if (error !== null) {
		console.log('exec error: ' + error);
	}
});